export const formConfig = [
    {
        "order": 1.0,
        "wizardSection": "Boas-vindas",
        "newSection": "Tela de abertura",
        "uiTitle": "Tela de abertura",
        "label": "Introdução ao Projeto",
        "component": "StaticText",
        "content": "Bem-vindo ao Livrão da Família. Este projeto nasceu para preservar as histórias e memórias que formam a nossa identidade. Como Representante Familiar, você desempenha um papel fundamental na construção deste legado. Suas informações serão salvas automaticamente. Vamos começar?"
    },
    {
        "order": 1.1,
        "wizardSection": "Boas-vindas",
        "newSection": "Tela de abertura",
        "uiTitle": "Tela de abertura",
        "label": "Logomarca",
        "component": "Logomarca do livrão"
    },
    {
        "order": 1.2,
        "wizardSection": "Boas-vindas",
        "newSection": "Tela de abertura",
        "uiTitle": "Tela de abertura",
        "label": "Botão",
        "component": "Prosseguir/de acordo"
    },
    {
        "order": 2.0,
        "wizardSection": "Representative",
        "newSection": "Informações do Representante",
        "uiTitle": "1. Informações do Representante",
        "label": "Nome do Representante",
        "component": "EditableField",
        "fieldId": "repName",
        "helpText": "Preenchido automaticamente pelo login de quem está realizando o preenchimento.",
        "required": true
    },
    {
        "order": 2.1,
        "wizardSection": "Representative",
        "newSection": "Informações do Representante",
        "uiTitle": "1. Informações do Representante",
        "label": "E-mail",
        "component": "InputField",
        "fieldId": "repEmail",
        "disabled": true,
        "helpText": "Chave única de identificação da família.",
        "required": true
    },

    {
        "order": 2.3,
        "wizardSection": "Representative",
        "newSection": "Informações do Representante",
        "uiTitle": "1. Informações do Representante",
        "label": "Profissão / Ocupação",
        "component": "InputField",
        "fieldId": "repProfession",
        "helpText": "Sua principal atividade profissional.",
        "required": false
    },



    {
        "order": 4.0,
        "wizardSection": "General",
        "newSection": " ",
        "uiTitle": "2. Árvore da Família",
        "label": " ",
        "component": "FamilyTreeSelector",
        "fieldId": "relationshipInfo"
    },


    {
        "order": 5.6,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "component": "UploadComponent",
        "label": "Foto para Identificação",
        "fieldId": "fotoIdentificacao",
        "helpText": "Uma foto clara do rosto para a árvore genealógica.",
        "placeholder": "DO ROSTO (TIPO 3X4 OU RECORTE)",
        "maxFiles": 1,
        "allowUnknown": false
    },
    {
        "order": 4.9,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "3. Identidade",
        "label": "Nome Completo",
        "component": "InputField",
        "fieldId": "nomeCompleto",
        "helpText": "Com todos os sobrenomes. Nome principal do biografado, incluindo todos os sobrenomes.",
        "required": true
    },

    {
        "order": 5.0,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "3. Identidade",
        "label": "Data de Nascimento",
        "component": "DateInputField",
        "fieldId": "dataNascimento",
        "helpText": "Informe a data completa. Se não souber, clique em 'Não Sei'.",
        "required": true,
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 5.06,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Sobrenomes de Solteiro(a)",
        "component": "InputField",
        "fieldId": "sobrenomesSolteiro",
        "conditionalRule": "sexo == 'Feminino'",
        "helpText": "Sobrenome de nascimento (importante para o registro genealógico).",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 5.1,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Apelido",
        "component": "InputField",
        "fieldId": "apelido",
        "helpText": "Como a pessoa é ou era carinhosamente chamada.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 5.8,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Religião",
        "component": "SelectField",
        "fieldId": "religiao",
        "helpText": "Crer em algo ou seguir uma tradição religiosa.",
        "allowUnknown": true,
        "allowReference": true,
        "options": [
            "Judaica",
            "Católica",
            "Evangélica",
            "Espírita",
            "Islamismo",
            "Budismo",
            "Sem Religião",
            "Outra"
        ]
    },
    {
        "order": 5.81,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Qual outra religião?",
        "component": "InputField",
        "fieldId": "religiao_outro",
        "conditionalRule": "religiao == 'Outra'",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 5.82,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Nome Hebraico",
        "component": "InputField",
        "fieldId": "nomeHebraico",
        "conditionalRule": "religiao == 'Judaica'",
        "helpText": "Nome religioso utilizado na comunidade ou sinagoga.",
        "allowNotApplicable": true,
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 5.2,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Nome do Pai",
        "component": "InputField",
        "fieldId": "nomePai",
        "helpText": "Nome completo do genitor do personagem histórico.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 5.3,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Nome da Mãe",
        "component": "InputField",
        "fieldId": "nomeMae",
        "helpText": "Nome completo da genitora do personagem histórico.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 5.05,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Sexo",
        "component": "SelectField",
        "fieldId": "sexo",
        "options": [
            "Masculino",
            "Feminino"
        ],
        "helpText": "Gênero de nascimento para direcionar as perguntas corretas do Livrão.",
        "allowUnknown": true,
        "allowReference": false
    },
    {
        "order": 5.7,
        "wizardSection": "Biografia",
        "newSection": "Identidade",
        "uiTitle": "4. Identidade",
        "label": "Local de Nascimento",
        "component": "LocationSelector",
        "fieldId": "localNascimento_pais",
        "helpText": "(Cidade, Estado / Região, País). Cidade, Estado e País onde o familiar nasceu.",
        "allowUnknown": true,
        "allowReference": true,
        "manualToggleField": "localNascimento_manual_toggle",
        "manualToggleLabel": "Não encontrei na lista"
    },
    {
        "order": 7.00,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Situação Conjugal",
        "component": "SelectField",
        "fieldId": "situacaoConjugal",
        "helpText": "Estado civil referente a esta união ou momento de vida.",
        "allowUnknown": true,
        "allowReference": true,
        "options": [
            "Solteiro",
            "Casado",
            "União Estável"
        ]
    },
    {
        "order": 7.01,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome Completo do Cônjuge",
        "component": "InputField",
        "fieldId": "nomeConjuge",
        "conditionalRule": "situacaoConjugal in 'Casado,Divorciado,Viúvo,União Estável'",
        "helpText": "Nome completo do parceiro(a); habilitado se houver registro de casamento.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.02,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Data de Nascimento do Cônjuge",
        "component": "DateInputField",
        "fieldId": "dataNascimentoConjuge",
        "conditionalRule": "situacaoConjugal in 'Casado,Divorciado,Viúvo,União Estável'",
        "helpText": "Data de nascimento da esposa ou marido.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.03,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Data do Casamento",
        "component": "DateInputField",
        "fieldId": "dataCasamento",
        "conditionalRule": "situacaoConjugal in 'Casado,Divorciado,Viúvo,União Estável'",
        "helpText": "Data em que foi realizada a união matrimonial.",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 7.031,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Celebrante / Rabino",
        "component": "InputField",
        "fieldId": "wedding_celebrant",
        "conditionalRule": "situacaoConjugal in 'Casado,Divorciado,Viúvo,União Estável'",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 7.032,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Local do Casamento",
        "component": "InputField",
        "fieldId": "wedding_location",
        "conditionalRule": "situacaoConjugal in 'Casado,Divorciado,Viúvo,União Estável'",
        "allowUnknown": true,
        "allowReference": true,
        "colSpan": 12
    },
    {
        "order": 7.033,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "component": "UploadComponent",
        "label": "Foto do Casamento",
        "fieldId": "wedding_photo",
        "conditionalRule": "situacaoConjugal in 'Casado,Divorciado,Viúvo,União Estável'",
        "helpText": "(Opcional). Arquivo da cerimônia.",
        "placeholder": "DO CASAMENTO",
        "maxFiles": 1,
        "allowUnknown": false,
        "colSpan": 12,
        "align": "left"
    },
    {
        "order": 7.04,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "component": "UploadComponent",
        "label": "Foto da Ketubá/Certidão de Casamento.",
        "fieldId": "fotoKetuba",
        "conditionalRule": "situacaoConjugal in 'Casado,Divorciado,Viúvo,União Estável'",
        "helpText": "(Opcional). Cópia da Ketubá.",
        "placeholder": "DA QUETUBÁ OU CERTIDÃO DE CASAMENTO",
        "maxFiles": 2,
        "allowUnknown": false,
        "colSpan": 12,
        "align": "right"
    },




    // --- SITUAÇÃO VITAL (7.4x) ---
    {
        "order": 7.40,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Situação Vital",
        "component": "SelectField",
        "fieldId": "situacaoVital",
        "helpText": "Define se o familiar está vivo ou se os campos de óbito devem ser exibidos.",
        "allowUnknown": true,
        "allowReference": true,
        "options": [
            "Vivo",
            "Falecido"
        ]
    },
    {
        "order": 7.41,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Data de Falecimento",
        "component": "DateInputField",
        "fieldId": "dataFalecimento",
        "conditionalRule": "situacaoVital == 'Falecido'",
        "helpText": "Se souber apenas o mês, coloque dia 01; se souber apenas o ano, coloque 01/01/ANO.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.42,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Local de Falecimento",
        "component": "LocationSelector",
        "fieldId": "localFalecimento",
        "conditionalRule": "situacaoVital == 'Falecido'",
        "helpText": "Cidade ou localidade onde ocorreu o óbito.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.43,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Cemitério (Onde está sepultado)",
        "component": "InputField",
        "fieldId": "cemiterio",
        "conditionalRule": "situacaoVital == 'Falecido'",
        "helpText": "Nome do cemitério onde o familiar foi sepultado.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.44,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Local Sepultamento",
        "component": "TextAreaField",
        "fieldId": "localSepultamento",
        "conditionalRule": "situacaoVital == 'Falecido'",
        "helpText": "Localização específica quadra, fileira, no.da sepultuta etc.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.45,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Foto da Certidão de Óbito",
        "component": "UploadComponent",
        "fieldId": "deathCertificate_photo",
        "conditionalRule": "situacaoVital == 'Falecido'",
        "maxFiles": 2,
        "placeholder": "DA CERTIDÃO DE ÓBITO",
        "colSpan": 12
    },

    // --- FILHOS (7.5x) ---
    {
        "order": 7.50,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Teve filhos?",
        "component": "SelectField",
        "fieldId": "qtdFilhos",
        "helpText": "Quantidade total de descendentes diretos.",
        "allowUnknown": true,
        "allowReference": true,
        "options": [
            "Nenhum", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"
        ]
    },
    {
        "order": 7.51,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Primogênito",
        "component": "InputField",
        "fieldId": "nomeFilho1",
        "conditionalRule": "qtdFilhos >= 1",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.52,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Segundo Filho",
        "component": "InputField",
        "fieldId": "nomeFilho2",
        "conditionalRule": "qtdFilhos >= 2",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.53,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Terceiro Filho",
        "component": "InputField",
        "fieldId": "nomeFilho3",
        "conditionalRule": "qtdFilhos >= 3",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.54,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Quarto Filho",
        "component": "InputField",
        "fieldId": "nomeFilho4",
        "conditionalRule": "qtdFilhos >= 4",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.55,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Quinto Filho",
        "component": "InputField",
        "fieldId": "nomeFilho5",
        "conditionalRule": "qtdFilhos >= 5",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.56,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Sexto Filho",
        "component": "InputField",
        "fieldId": "nomeFilho6",
        "conditionalRule": "qtdFilhos >= 6",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.57,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Sétimo Filho",
        "component": "InputField",
        "fieldId": "nomeFilho7",
        "conditionalRule": "qtdFilhos >= 7",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.58,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Oitavo Filho",
        "component": "InputField",
        "fieldId": "nomeFilho8",
        "conditionalRule": "qtdFilhos >= 8",
        "helpText": "Listagem nominal dos filhos do personagem histórico.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.59,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Nono Filho",
        "component": "InputField",
        "fieldId": "nomeFilho9",
        "conditionalRule": "qtdFilhos >= 9",
        "helpText": "Listagem nominal dos filhos do personagem histórico.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.60,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Décimo Filho",
        "component": "InputField",
        "fieldId": "nomeFilho10",
        "conditionalRule": "qtdFilhos >= 10",
        "helpText": "Listagem nominal dos filhos do personagem histórico.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.61,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Décimo Primeiro Filho",
        "component": "InputField",
        "fieldId": "nomeFilho11",
        "conditionalRule": "qtdFilhos >= 11"
    },
    {
        "order": 7.62,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Décimo Segundo Filho",
        "component": "InputField",
        "fieldId": "nomeFilho12",
        "conditionalRule": "qtdFilhos >= 12"
    },
    {
        "order": 7.63,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Décimo Terceiro Filho",
        "component": "InputField",
        "fieldId": "nomeFilho13",
        "conditionalRule": "qtdFilhos >= 13"
    },
    {
        "order": 7.64,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Décimo Quarto Filho",
        "component": "InputField",
        "fieldId": "nomeFilho14",
        "conditionalRule": "qtdFilhos >= 14"
    },
    {
        "order": 7.65,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Décimo Quinto Filho",
        "component": "InputField",
        "fieldId": "nomeFilho15",
        "conditionalRule": "qtdFilhos >= 15"
    },
    {
        "order": 7.66,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Nome do Décimo Sexto Filho",
        "component": "InputField",
        "fieldId": "nomeFilho16",
        "conditionalRule": "qtdFilhos >= 16"
    },

    // --- DESFECHO E NOVOS CASAMENTOS (Movidos para o final) ---
    {
        "order": 7.70,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Desfecho do Relacionamento",
        "component": "SingleSelectGroup",
        "fieldId": "marriageOutcome",
        "options": ["Foram felizes para sempre", "Divórcio", "Falecimento"],
        "conditionalRule": "situacaoConjugal in 'Casado,Viúvo,União Estável'",
        "helpText": "Indica como se encerrou a união (divórcio ou falecimento).",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.71,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Data do Divórcio / Separação",
        "component": "DateInputField",
        "fieldId": "dataDivorcio",
        "conditionalRule": "marriageOutcome == 'Divórcio'",
        "helpText": "Data da separação legal, se aplicável.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.72,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Data de Falecimento do Cônjuge",
        "component": "DateInputField",
        "fieldId": "dataFalecimentoConjuge",
        "conditionalRule": "marriageOutcome == 'Falecimento'",
        "helpText": "Registro da data de óbito do parceiro(a).",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.725,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Foto da Certidão de Óbito (Cônjuge)",
        "component": "UploadComponent",
        "fieldId": "spouseDeathCertificate_photo",
        "conditionalRule": "marriageOutcome == 'Falecimento'",
        "maxFiles": 2,
        "placeholder": "DA CERTIDÃO DE ÓBITO DO CÔNJUGE",
        "colSpan": 12
    },
    {
        "order": 7.73,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Família e vida",
        "label": "Casou-se novamente?",
        "component": "CheckboxField",
        "fieldId": "remarried_1",
        "conditionalRule": "marriageOutcome in 'Divórcio,Falecimento'",
        "helpText": "Checkbox para indicar a ocorrência de novas núpcias.",
        "allowUnknown": true,
        "allowReference": true
    },

    // --- CASAMENTO 2 (7.74x) ---
    {
        "order": 7.74,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome Completo do 2º Cônjuge",
        "component": "InputField",
        "fieldId": "spouseName_2",
        "conditionalRule": "remarried_1",
        "helpText": "Identificação do segundo parceiro(a) matrimonial.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.75,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Data de Nascimento (2º Cônjuge)",
        "component": "DateInputField",
        "fieldId": "spouseBirthDate_2",
        "conditionalRule": "remarried_1",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.76,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Data do 2º Casamento",
        "component": "DateInputField",
        "fieldId": "marriageDate_2",
        "conditionalRule": "remarried_1",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.77,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Desfecho do 2º Casamento",
        "component": "SingleSelectGroup",
        "fieldId": "marriageOutcome_2",
        "options": ["Foram felizes para sempre", "Divórcio", "Falecimento"],
        "conditionalRule": "remarried_1",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.78,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Data do Divórcio (2º Casamento)",
        "component": "DateInputField",
        "fieldId": "divorceDate_2",
        "conditionalRule": "marriageOutcome_2 == 'Divórcio'",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.79,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Data de Falecimento (2º Cônjuge)",
        "component": "DateInputField",
        "fieldId": "spouseDeathDate_2",
        "conditionalRule": "marriageOutcome_2 == 'Falecimento'",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.7905,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Foto da Certidão de Óbito (2º Cônjuge)",
        "component": "UploadComponent",
        "fieldId": "spouseDeathCertificate_photo_2",
        "conditionalRule": "marriageOutcome_2 == 'Falecimento'",
        "maxFiles": 2,
        "placeholder": "DA CERTIDÃO DE ÓBITO",
        "colSpan": 12
    },
    {
        "order": 7.771,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Local do 2º Casamento",
        "component": "InputField",
        "fieldId": "wedding_location_2",
        "conditionalRule": "remarried_1",
        "colSpan": 12
    },
    {
        "order": 7.791,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "component": "UploadComponent",
        "label": "Foto do Casamento",
        "fieldId": "wedding_photo_2",
        "conditionalRule": "remarried_1",
        "maxFiles": 1,
        "placeholder": "DO CASAMENTO",
        "colSpan": 12,
        "align": "left"
    },
    {
        "order": 7.792,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "component": "UploadComponent",
        "label": "Foto da Ketubá/Certidão de Casamento.",
        "fieldId": "ketubaUpload_2",
        "conditionalRule": "remarried_1",
        "maxFiles": 2,
        "placeholder": "DA QUETUBÁ OU CERTIDÃO DE CASAMENTO",
        "colSpan": 12,
        "align": "right"
    },
    {
        "order": 7.793,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Teve filhos neste 2º casamento?",
        "component": "SelectField",
        "fieldId": "qtdFilhos_2",
        "conditionalRule": "remarried_1",
        "options": ["Nenhum", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"]
    },
    {
        "order": 7.794,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 1º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho1_2",
        "conditionalRule": "qtdFilhos_2 >= 1"
    },
    {
        "order": 7.795,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 2º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho2_2",
        "conditionalRule": "qtdFilhos_2 >= 2"
    },
    {
        "order": 7.796,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 3º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho3_2",
        "conditionalRule": "qtdFilhos_2 >= 3"
    },
    {
        "order": 7.797,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 4º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho4_2",
        "conditionalRule": "qtdFilhos_2 >= 4"
    },
    {
        "order": 7.798,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 5º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho5_2",
        "conditionalRule": "qtdFilhos_2 >= 5"
    },
    {
        "order": 7.799,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 6º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho6_2",
        "conditionalRule": "qtdFilhos_2 >= 6"
    },
    {
        "order": 7.7991,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 7º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho7_2",
        "conditionalRule": "qtdFilhos_2 >= 7"
    },
    {
        "order": 7.7992,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 8º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho8_2",
        "conditionalRule": "qtdFilhos_2 >= 8"
    },
    {
        "order": 7.7993,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 9º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho9_2",
        "conditionalRule": "qtdFilhos_2 >= 9"
    },
    {
        "order": 7.7994,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 10º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho10_2",
        "conditionalRule": "qtdFilhos_2 >= 10"
    },
    {
        "order": 7.7995,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 11º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho11_2",
        "conditionalRule": "qtdFilhos_2 >= 11"
    },
    {
        "order": 7.7996,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 12º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho12_2",
        "conditionalRule": "qtdFilhos_2 >= 12"
    },
    {
        "order": 7.7997,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 13º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho13_2",
        "conditionalRule": "qtdFilhos_2 >= 13"
    },
    {
        "order": 7.7998,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 14º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho14_2",
        "conditionalRule": "qtdFilhos_2 >= 14"
    },
    {
        "order": 7.7999,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 15º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho15_2",
        "conditionalRule": "qtdFilhos_2 >= 15"
    },
    {
        "order": 7.79991,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Nome do 16º Filho (2º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho16_2",
        "conditionalRule": "qtdFilhos_2 >= 16"
    },
    {
        "order": 7.80,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (2º Casamento)",
        "label": "Casou-se novamente (após 2º)?",
        "component": "CheckboxField",
        "fieldId": "remarried_2",
        "conditionalRule": "marriageOutcome_2 in 'Divórcio,Falecimento'",
        "allowUnknown": true,
        "allowReference": true
    },

    // --- CASAMENTO 3 (7.81x) ---
    {
        "order": 7.81,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome Completo do 3º Cônjuge",
        "component": "InputField",
        "fieldId": "spouseName_3",
        "conditionalRule": "remarried_2",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 7.82,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Data de Nascimento (3º Cônjuge)",
        "component": "DateInputField",
        "fieldId": "spouseBirthDate_3",
        "conditionalRule": "remarried_2 == true"
    },
    {
        "order": 7.83,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Data do 3º Casamento",
        "component": "DateInputField",
        "fieldId": "marriageDate_3",
        "conditionalRule": "remarried_2 == true"
    },
    {
        "order": 7.84,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Desfecho do 3º Casamento",
        "component": "SingleSelectGroup",
        "fieldId": "marriageOutcome_3",
        "options": ["Foram felizes para sempre", "Divórcio", "Falecimento"],
        "conditionalRule": "remarried_2 == true"
    },
    {
        "order": 7.85,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Data do Divórcio (3º Casamento)",
        "component": "DateInputField",
        "fieldId": "divorceDate_3",
        "conditionalRule": "marriageOutcome_3 == 'Divórcio'"
    },
    {
        "order": 7.86,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Data de Falecimento (3º Cônjuge)",
        "component": "DateInputField",
        "fieldId": "spouseDeathDate_3",
        "conditionalRule": "marriageOutcome_3 == 'Falecimento'"
    },
    {
        "order": 7.8605,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Foto da Certidão de Óbito (3º Cônjuge)",
        "component": "UploadComponent",
        "fieldId": "spouseDeathCertificate_photo_3",
        "conditionalRule": "marriageOutcome_3 == 'Falecimento'",
        "maxFiles": 2,
        "placeholder": "DA CERTIDÃO DE ÓBITO",
        "colSpan": 12
    },
    {
        "order": 7.851,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Local do 3º Casamento",
        "component": "InputField",
        "fieldId": "wedding_location_3",
        "conditionalRule": "remarried_2",
        "colSpan": 12
    },
    {
        "order": 7.861,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "component": "UploadComponent",
        "label": "Foto do Casamento",
        "fieldId": "wedding_photo_3",
        "conditionalRule": "remarried_2",
        "maxFiles": 1,
        "placeholder": "DO CASAMENTO",
        "colSpan": 12,
        "align": "left"
    },
    {
        "order": 7.862,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "component": "UploadComponent",
        "label": "Foto da Ketubá/Certidão de Casamento.",
        "fieldId": "ketubaUpload_3",
        "conditionalRule": "remarried_2",
        "maxFiles": 2,
        "placeholder": "DA QUETUBÁ OU CERTIDÃO DE CASAMENTO",
        "colSpan": 12,
        "align": "right"
    },
    {
        "order": 7.863,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Teve filhos neste 3º casamento?",
        "component": "SelectField",
        "fieldId": "qtdFilhos_3",
        "conditionalRule": "remarried_2",
        "options": ["Nenhum", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"]
    },
    {
        "order": 7.864,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 1º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho1_3",
        "conditionalRule": "qtdFilhos_3 >= 1"
    },
    {
        "order": 7.865,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 2º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho2_3",
        "conditionalRule": "qtdFilhos_3 >= 2"
    },
    {
        "order": 7.866,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 3º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho3_3",
        "conditionalRule": "qtdFilhos_3 >= 3"
    },
    {
        "order": 7.867,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 4º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho4_3",
        "conditionalRule": "qtdFilhos_3 >= 4"
    },
    {
        "order": 7.868,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 5º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho5_3",
        "conditionalRule": "qtdFilhos_3 >= 5"
    },
    {
        "order": 7.869,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 6º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho6_3",
        "conditionalRule": "qtdFilhos_3 >= 6"
    },
    {
        "order": 7.8691,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 7º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho7_3",
        "conditionalRule": "qtdFilhos_3 >= 7"
    },
    {
        "order": 7.8692,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 8º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho8_3",
        "conditionalRule": "qtdFilhos_3 >= 8"
    },
    {
        "order": 7.8693,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 9º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho9_3",
        "conditionalRule": "qtdFilhos_3 >= 9"
    },
    {
        "order": 7.8694,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 10º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho10_3",
        "conditionalRule": "qtdFilhos_3 >= 10"
    },
    {
        "order": 7.8695,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 11º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho11_3",
        "conditionalRule": "qtdFilhos_3 >= 11"
    },
    {
        "order": 7.8696,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 12º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho12_3",
        "conditionalRule": "qtdFilhos_3 >= 12"
    },
    {
        "order": 7.8697,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 13º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho13_3",
        "conditionalRule": "qtdFilhos_3 >= 13"
    },
    {
        "order": 7.8698,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 14º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho14_3",
        "conditionalRule": "qtdFilhos_3 >= 14"
    },
    {
        "order": 7.8699,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 15º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho15_3",
        "conditionalRule": "qtdFilhos_3 >= 15"
    },
    {
        "order": 7.86991,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Nome do 16º Filho (3º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho16_3",
        "conditionalRule": "qtdFilhos_3 >= 16"
    },
    {
        "order": 7.87,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (3º Casamento)",
        "label": "Casou-se novamente (após 3º)?",
        "component": "CheckboxField",
        "fieldId": "remarried_3",
        "conditionalRule": "marriageOutcome_3 in 'Divórcio,Falecimento'"
    },

    // --- CASAMENTO 4 (7.88x) ---
    {
        "order": 7.88,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome Completo do 4º Cônjuge",
        "component": "InputField",
        "fieldId": "spouseName_4",
        "conditionalRule": "remarried_3 == true"
    },
    {
        "order": 7.89,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Data de Nascimento (4º Cônjuge)",
        "component": "DateInputField",
        "fieldId": "spouseBirthDate_4",
        "conditionalRule": "remarried_3 == true"
    },
    {
        "order": 7.90,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Data do 4º Casamento",
        "component": "DateInputField",
        "fieldId": "marriageDate_4",
        "conditionalRule": "remarried_3 == true"
    },
    {
        "order": 7.91,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Desfecho do 4º Casamento",
        "component": "SingleSelectGroup",
        "fieldId": "marriageOutcome_4",
        "options": ["Foram felizes para sempre", "Divórcio", "Falecimento"],
        "conditionalRule": "remarried_3 == true"
    },
    {
        "order": 7.92,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Data do Divórcio (4º Casamento)",
        "component": "DateInputField",
        "fieldId": "divorceDate_4",
        "conditionalRule": "marriageOutcome_4 == 'Divórcio'"
    },
    {
        "order": 7.93,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Data de Falecimento (4º Cônjuge)",
        "component": "DateInputField",
        "fieldId": "spouseDeathDate_4",
        "conditionalRule": "marriageOutcome_4 == 'Falecimento'"
    },
    {
        "order": 7.9305,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Foto da Certidão de Óbito (4º Cônjuge)",
        "component": "UploadComponent",
        "fieldId": "spouseDeathCertificate_photo_4",
        "conditionalRule": "marriageOutcome_4 == 'Falecimento'",
        "maxFiles": 2,
        "placeholder": "DA CERTIDÃO DE ÓBITO",
        "colSpan": 12
    },
    {
        "order": 7.911,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Local do 4º Casamento",
        "component": "InputField",
        "fieldId": "wedding_location_4",
        "conditionalRule": "remarried_3 == true",
        "colSpan": 12
    },
    {
        "order": 7.931,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "component": "UploadComponent",
        "label": "Foto do Casamento",
        "fieldId": "wedding_photo_4",
        "conditionalRule": "remarried_3 == true",
        "maxFiles": 1,
        "placeholder": "DO CASAMENTO",
        "colSpan": 12,
        "align": "left"
    },
    {
        "order": 7.932,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "component": "UploadComponent",
        "label": "Foto da Ketubá/Certidão de Casamento.",
        "fieldId": "ketubaUpload_4",
        "conditionalRule": "remarried_3 == true",
        "maxFiles": 2,
        "placeholder": "DA QUETUBÁ OU CERTIDÃO DE CASAMENTO",
        "colSpan": 12,
        "align": "right"
    },
    {
        "order": 7.933,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Teve filhos neste 4º casamento?",
        "component": "SelectField",
        "fieldId": "qtdFilhos_4",
        "conditionalRule": "remarried_3 == true",
        "options": ["Nenhum", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"]
    },
    {
        "order": 7.934,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 1º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho1_4",
        "conditionalRule": "qtdFilhos_4 >= 1"
    },
    {
        "order": 7.935,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 2º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho2_4",
        "conditionalRule": "qtdFilhos_4 >= 2"
    },
    {
        "order": 7.936,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 3º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho3_4",
        "conditionalRule": "qtdFilhos_4 >= 3"
    },
    {
        "order": 7.937,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 4º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho4_4",
        "conditionalRule": "qtdFilhos_4 >= 4"
    },
    {
        "order": 7.938,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 5º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho5_4",
        "conditionalRule": "qtdFilhos_4 >= 5"
    },
    {
        "order": 7.939,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 6º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho6_4",
        "conditionalRule": "qtdFilhos_4 >= 6"
    },
    {
        "order": 7.9391,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 7º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho7_4",
        "conditionalRule": "qtdFilhos_4 >= 7"
    },
    {
        "order": 7.9392,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 8º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho8_4",
        "conditionalRule": "qtdFilhos_4 >= 8"
    },
    {
        "order": 7.9393,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 9º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho9_4",
        "conditionalRule": "qtdFilhos_4 >= 9"
    },
    {
        "order": 7.9394,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 10º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho10_4",
        "conditionalRule": "qtdFilhos_4 >= 10"
    },
    {
        "order": 7.9395,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 11º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho11_4",
        "conditionalRule": "qtdFilhos_4 >= 11"
    },
    {
        "order": 7.9396,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 12º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho12_4",
        "conditionalRule": "qtdFilhos_4 >= 12"
    },
    {
        "order": 7.9397,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 13º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho13_4",
        "conditionalRule": "qtdFilhos_4 >= 13"
    },
    {
        "order": 7.9398,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 14º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho14_4",
        "conditionalRule": "qtdFilhos_4 >= 14"
    },
    {
        "order": 7.9399,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 15º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho15_4",
        "conditionalRule": "qtdFilhos_4 >= 15"
    },
    {
        "order": 7.93991,
        "wizardSection": "FamilyVital",
        "newSection": "Família e vida",
        "uiTitle": "Preencher dados do novo cônjuge (4º Casamento)",
        "label": "Nome do 16º Filho (4º Casam.)",
        "component": "InputField",
        "fieldId": "nomeFilho16_4",
        "conditionalRule": "qtdFilhos_4 >= 16"
    },
    {
        "order": 8.1,
        "wizardSection": "LifeCulture",
        "newSection": "Educação, trabalho e realizações",
        "uiTitle": "8. Educação, trabalho e realizações",
        "label": "Grau de Instrução",
        "component": "SelectField",
        "fieldId": "grauInstrucao",
        "helpText": "Nível de escolaridade. Legenda: Atual (em PRETO), de 1971 a 1996 (em AZUL), Pré-1971 (em VERDE).",
        "allowUnknown": true,
        "allowReference": true,
        "options": [
            "Analfabeto",
            "Alfabetizado",
            "Instrução em casa",
            "Fundamental incompleto, 1º grau incompleto, primário ou ginásio incompleto",
            "Fundamental completo, 1º grau completo, ginasial completo",
            "Médio incompleto, 2º grau incompleto, científico ou clássico incompleto",
            "Médio completo, 2º grau completo, científico, clássico, técnico ou normal",
            "Superior incompleto, 3º grau incompleto, universitário incompleto",
            "Superior completo, 3º grau completo, universitário completo",
            "Pós graduado"
        ]
        ,
        "manualToggleField": "grauInstrucao_toggle",
        "manualToggleLabel": "Não encontrei na lista"
    },
    {
        "order": 8.2,
        "wizardSection": "LifeCulture",
        "newSection": "Vida e Trabalho",
        "uiTitle": "8. Vida e Trabalho",
        "label": "Escolas e Universidades (Detalhes)",
        "component": "TextAreaField",
        "fieldId": "escolasUniversidades",
        "helpText": "Instituições de ensino onde o biografado estudou.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 8.3,
        "wizardSection": "LifeCulture",
        "newSection": "Vida e Trabalho",
        "uiTitle": "8. Vida e Trabalho",
        "label": "Ocupação Principal",
        "component": "TextAreaField",
        "fieldId": "ocupacaoPrincipal",
        "helpText": "Liste as principais profissões exercidas ao longo da vida, separadas por vírgula.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 8.4,
        "wizardSection": "LifeCulture",
        "newSection": "Vida e Trabalho",
        "uiTitle": "8. Vida e Trabalho",
        "label": "Locais de Trabalho (Empresas/Negócios)",
        "component": "TextAreaField",
        "fieldId": "locaisTrabalho",
        "helpText": "Empresas ou instituições onde exerceu suas atividades profissionais.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 8.5,
        "wizardSection": "LifeCulture",
        "newSection": "Vida e Trabalho",
        "uiTitle": "8. Vida e Trabalho",
        "label": "Realizações e Prêmios",
        "component": "InputField",
        "fieldId": "realizacoesPremios",
        "helpText": "Méritos, honrarias ou conquistas de destaque.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 9.1,
        "wizardSection": "LifeCulture",
        "newSection": "Domicílio e viagens",
        "uiTitle": "9. Domicílio e viagens",
        "label": "Cidades Onde Morou (Cronológico com Anos)",
        "component": "TextAreaField",
        "fieldId": "cidadesMorou",
        "helpText": "Lista cronológica das residências (Ex: Belém 1960-1975).",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 9.2,
        "wizardSection": "LifeCulture",
        "newSection": "Domicílio e viagens",
        "uiTitle": "9. Domicílio e viagens",
        "label": "Locais que Conheceu (Viagens, etc)",
        "component": "TextAreaField",
        "fieldId": "locaisConheceu",
        "helpText": "Registro de viagens e lugares visitados pelo familiar.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.1,
        "wizardSection": "LifeCulture",
        "newSection": "Vida Social e Comunitária",
        "uiTitle": "10. Vida Social e Comunitária",
        "label": "Amizades Marcantes",
        "component": "TextAreaField",
        "fieldId": "amizadesMarcantes",
        "helpText": "Nomes de amigos próximos e pessoas influentes no círculo social.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.15,
        "wizardSection": "VidaJudaica",
        "newSection": "Vida Judaica e Comunitária",
        "uiTitle": "10. Vida Judaica",
        "label": "Afiliação Comunitária",
        "component": "SelectField",
        "fieldId": "community",
        "helpText": "Entidade vinculada (Ex: Centro Israelita do Pará, Comitê Amazonas).",
        "allowUnknown": true,
        "allowReference": true,
        "options": [
            "Centro Israelita do Pará (CIP)",
            "Comitê Israelita do Amazonas (CIAM)",
            "União Israelita Shel Guemilut Chassadim",
            "Outros"
        ]
    },
    {
        "order": 10.16,
        "wizardSection": "VidaJudaica",
        "newSection": "Vida Judaica e Comunitária",
        "uiTitle": "10. Vida Judaica",
        "label": "Qual outra comunidade?",
        "component": "InputField",
        "fieldId": "communityOther",
        "conditionalRule": "community == 'Outros'",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.2,
        "wizardSection": "VidaJudaica",
        "newSection": "Vida Judaica e Comunitária",
        "uiTitle": "10. Vida Judaica",
        "label": "Atuação Comunitária (Cargos, Atividades)",
        "component": "InputField",
        "fieldId": "atuacaoComunitaria",
        "helpText": "Vida comunitária e cargos ocupados em instituições.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.625,
        "wizardSection": "VidaJudaica",
        "newSection": "Nascimento Judaico",
        "uiTitle": "10. Vida Judaica",
        "label": "Fez as Fadas / Zeved Habat?",
        "component": "CheckboxField",
        "fieldId": "did_fadas",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.01,
        "wizardSection": "VidaJudaica",
        "newSection": "Vida Social e Comunitária",
        "uiTitle": "10. Vida Judaica",
        "label": "Aviso de Gênero",
        "component": "WarningMessage",
        "fieldId": "gender_warning",
        "helpText": "Por favor, para vermos as perguntas de rituais corretas para você, preencha o campo 'Sexo' na aba 'Identidade'.",
        "allowReference": false
    },
    {
        "order": 10.63,
        "wizardSection": "VidaJudaica",
        "newSection": "Vida Social e Comunitária",
        "uiTitle": "10. Vida Judaica",
        "label": "Sinagoga que Frequentava",
        "component": "InputField",
        "fieldId": "sinagogaFrequentava",
        "helpText": "Templo religioso que o familiar costumava frequentar.",
        "allowUnknown": true,
        "allowReference": true
    },

    {
        "order": 10.5,
        "wizardSection": "LifeCulture",
        "newSection": "Vida Social e Comunitária",
        "uiTitle": "10. Vida Social e Comunitária",
        "label": "Hobbies (Esporte, Leitura, Música...)",
        "component": "TextAreaField",
        "fieldId": "hobbies",
        "helpText": "Interesses pessoais como esportes, leitura ou música, separados por vírgula.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.55,
        "wizardSection": "VidaJudaica",
        "newSection": "Nascimento Judaico",
        "uiTitle": "10. Vida Judaica",
        "label": "Fez Brit Millah?",
        "component": "CheckboxField",
        "fieldId": "did_brit_millah",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.6,
        "wizardSection": "VidaJudaica",
        "newSection": "Nascimento Judaico",
        "uiTitle": "10. Vida Judaica",
        "label": "Data do Brit Millah",
        "helpText": "Ritual de Admissão à Aliança.",
        "component": "DateInputField",
        "fieldId": "brit_millah_date",
        "conditionalRule": "did_brit_millah",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 10.61,
        "wizardSection": "VidaJudaica",
        "newSection": "Nascimento Judaico",
        "uiTitle": "10. Vida Judaica",
        "label": "Local do Brit Millah",
        "component": "InputField",
        "fieldId": "brit_millah_location",
        "conditionalRule": "did_brit_millah",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 10.62,
        "wizardSection": "VidaJudaica",
        "newSection": "Nascimento Judaico",
        "uiTitle": "10. Vida Judaica",
        "label": "Mohel",
        "helpText": "Responsável pela circuncisão.",
        "component": "InputField",
        "fieldId": "brit_millah_responsible",
        "conditionalRule": "did_brit_millah",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.66,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Fez Bar Mitzvá?",
        "component": "CheckboxField",
        "fieldId": "did_bar_mitzva",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.661,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Data do Bar Mitzvá",
        "component": "DateInputField",
        "fieldId": "bar_mitzva_date",
        "conditionalRule": "did_bar_mitzva",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 10.662,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Local do Bar Mitzvá",
        "component": "InputField",
        "fieldId": "bar_mitzva_location",
        "conditionalRule": "did_bar_mitzva",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },

    {
        "order": 10.663,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Professor de Hebraico/Bar Mitzvá",
        "component": "InputField",
        "fieldId": "professorHebraico_bar",
        "conditionalRule": "did_bar_mitzva",
        "helpText": "Nome do professor que o preparou para o Bar Mitzvá.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.67,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Fez Bat Mitzvá?",
        "component": "CheckboxField",
        "fieldId": "did_bat_mitzva",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.63,
        "wizardSection": "VidaJudaica",
        "newSection": "Nascimento Judaico",
        "uiTitle": "10. Vida Judaica",
        "label": "Data das Fadas / Zeved Habat",
        "helpText": "Ritual de nomeação para meninas.",
        "component": "DateInputField",
        "fieldId": "fadas_date",
        "conditionalRule": "did_fadas",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 10.671,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Data do Bat Mitzvá",
        "component": "DateInputField",
        "fieldId": "bat_mitzva_date",
        "conditionalRule": "did_bat_mitzva",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 10.672,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Local do Bat Mitzvá",
        "component": "InputField",
        "fieldId": "bat_mitzva_location",
        "conditionalRule": "did_bat_mitzva",
        "allowUnknown": true,
        "allowReference": true,
        "halfWidth": true
    },
    {
        "order": 10.673,
        "wizardSection": "VidaJudaica",
        "newSection": "Maioridade Judaica",
        "uiTitle": "10. Vida Judaica",
        "label": "Professor de Hebraico/Bat Mitzvá",
        "component": "InputField",
        "fieldId": "professorHebraico_bat",
        "conditionalRule": "did_bat_mitzva",
        "helpText": "Nome do(a) professor(a) que a preparou para o Bat Mitzvá.",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.7,
        "wizardSection": "VidaJudaica",
        "newSection": "Vida Social e Comunitária",
        "uiTitle": "10. Vida Judaica",
        "label": "Movimentos Juvenis (Grupo e Período)",
        "component": "TextAreaField",
        "fieldId": "youth_movements",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 10.8,
        "wizardSection": "LifeCulture",
        "newSection": "Vida Social e Comunitária",
        "uiTitle": "10. Vida Social e Comunitária",
        "label": "Outras Habilidades",
        "component": "TextAreaField",
        "fieldId": "additional_skills",
        "allowUnknown": true,
        "allowReference": true
    },
    {
        "order": 11.1,
        "wizardSection": "História",
        "newSection": "Memórias Vivas",
        "uiTitle": "11. Memórias Vivas (H)",
        "label": "Orientação para Biografia",
        "component": "StaticText",
        "content": "Agora que já registramos os dados cronológicos, este é o espaço dedicado à alma da biografia. Descreva traços de personalidade, desafios superados, valores pessoais e aquelas anedotas curiosas que só a família conhece. Pense no que você gostaria que as futuras gerações soubessem sobre quem essa pessoa realmente foi."
    },
    {
        "order": 11.15,
        "wizardSection": "História",
        "newSection": "Memórias Vivas",
        "uiTitle": "11. Memórias Vivas (H)",
        "label": "Termos em Hakitia",
        "component": "RichMediaInput",
        "fieldId": "hakitia_expressions",
        "helpText": "O Hakitia é a alma da nossa ancestralidade marroquina. Use este espaço para registrar termos, 'refranes', palavras carinhosas ou envie áudios/vídeos recordando pronúncias.",
        "placeholder": "(Campo de texto livre ou envio de mídia)",
        "allowReference": true
    },
    {
        "order": 11.2,
        "wizardSection": "História",
        "newSection": "Memórias Vivas",
        "uiTitle": "11. Memórias Vivas (H)",
        "label": "Resumo Histórico",
        "component": "RichMediaInput",
        "fieldId": "resumoHistorico",
        "placeholder": "(Campo de texto livre para a biografia)"
        ,
        "allowReference": true
    },
    {
        "order": 11.3,
        "wizardSection": "História",
        "newSection": "Memórias Vivas",
        "uiTitle": "11. Memórias Vivas (H)",
        "label": "Relatos Adicionais",
        "component": "RichMediaInput",
        "fieldId": "relatosAdicionais",
        "placeholder": "(conte uma historia que marcou a vida dele na comunidade)"
        ,
        "allowReference": true
    },

];
